name: cdktf
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.04
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: install cdk terraform
        run: npm install --global cdktf-cli
      - name: check
        run: 
          cdktf get
