name: cdktf
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.04
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          # github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: install cdk terraform
        run: |
          npm install --global cdktf-cli
          npm install
          cdktf get
      # - name: check
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}     
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: 
      #     cdktf get
      - name: cdktf get
        run: cdktf get
    # - name: Deploy 
    #   env:
    #     GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
    #   run: "cd cdktf.out && rm -rf .terraform && terraform init && terraform apply -auto-approve"             